version: '3'

services:
  onepieceapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile

    image: onepiece-docker
    container_name: onepieceapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${limit}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: mongo-opdb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-one-piece
    # volumes:
    #   - ./mongo:/data/db